# Generated by Django 5.1.4 on 2025-01-08 08:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AvailableTrigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Zap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_identifier', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zaps', to='zap_hooks.user')),
            ],
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_identifier', models.CharField(max_length=255)),
                ('metadata', models.JSONField(default=dict)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='zap_hooks.availabletrigger')),
                ('zap', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zap_trigger', to='zap_hooks.zap')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_id', models.CharField(max_length=255)),
                ('metadata', models.JSONField(default=dict)),
                ('sorting_order', models.IntegerField(default=0)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='zap_hooks.availableaction')),
                ('zap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='zap_hooks.zap')),
            ],
        ),
        migrations.CreateModel(
            name='ZapRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metadata', models.JSONField(default=dict)),
                ('zap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zap_runs', to='zap_hooks.zap')),
            ],
        ),
        migrations.CreateModel(
            name='ZapRunOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zap_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zap_run_outbox', to='zap_hooks.zaprun')),
            ],
        ),
    ]
